name: Publish CI

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
            - name: Install packages
              run: npm ci
            - name: Build packages
              run: npm run build -- ngx-navigation
            - name: Publish packages
              run: ./scripts/publish.sh
              env:
                  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
